# Generated by Django 2.0.4 on 2018-05-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
