# Generated by Django 2.0.4 on 2018-04-26 19:43

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('shortcode', models.CharField(blank=True, max_length=20, null=True)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('owner_id', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('other_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('taged_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=50)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_video', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='NEW', max_length=10)),
            ],
        ),
    ]
