# Generated by Django 2.0.4 on 2018-05-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180512_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_src',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
