# Generated by Django 2.0.4 on 2018-05-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180513_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
