# Generated by Django 2.0.4 on 2018-05-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180513_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
