# Generated by Django 2.0.4 on 2018-05-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
