# Generated by Django 2.0.4 on 2018-05-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180521_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(default='INSTAGRAM', max_length=25),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='NEW', max_length=10),
        ),
    ]
