# Generated by Django 2.0.4 on 2018-05-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180521_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='caption_tmp',
        ),
    ]
