# Generated by Django 2.0.4 on 2018-05-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='other_tags',
            new_name='tags',
        ),
    ]
