# Generated by Django 2.0.4 on 2018-05-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_tagblacklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_url',
            new_name='image_hd',
        ),
    ]
