# Generated by Django 2.0.4 on 2018-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20180524_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_sm',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
