# Generated by Django 2.0.4 on 2018-05-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_image_sm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video_url',
            new_name='video_hd',
        ),
    ]
