# Generated by Django 2.0.4 on 2018-05-25 10:55

from django.db import migrations, models

import adictaf.utilities.common


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shortcode',
            field=models.CharField(default=adictaf.utilities.common.id_generator, max_length=20),
        ),
    ]
