# Generated by Django 2.0.4 on 2018-06-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
