# Generated by Django 2.0.4 on 2018-06-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='ADDICTAF', max_length=20),
        ),
        migrations.AddField(
            model_name='username',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
