# Generated by Django 2.0.4 on 2018-06-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20180616_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gag_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
