# Generated by Django 2.0.4 on 2018-06-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_post_gag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
