# Generated by Django 2.0.4 on 2018-07-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_gaglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
