# Generated by Django 2.0.4 on 2018-04-26 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('username', models.CharField(max_length=200, unique=True)),
                ('follower_count', models.PositiveIntegerField(blank=True, null=True)),
                ('following_count', models.PositiveIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('posts', models.PositiveIntegerField(blank=True, null=True)),
                ('usertags_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='NEW', max_length=10)),
                ('estimate_location', models.CharField(blank=True, max_length=100)),
                ('estimate_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
