# Generated by Django 2.0.4 on 2018-05-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='requests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
