# Generated by Django 2.0.4 on 2018-07-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180710_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_likes_to_like',
            field=models.IntegerField(default=0),
        ),
    ]
